[pytest]
testpaths = tests
asyncio_mode = auto
filterwarnings =
    error::telegram.warnings.PTBDeprecationWarning
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore:.*anyio\.abc\.BlockingPortal.*:DeprecationWarning
